/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import dbClasses.ConexaoJDBC;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class TabelaPesquisaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TabelaCliente
     */
    ConexaoJDBC con = new ConexaoJDBC();
    
    public TabelaPesquisaCliente() {
        con.conecta();
        initComponents();
        preencherTabela("select nome,logadouro,e_mail,cpf from tb_cliente order by nome");
        con.disconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PainelPesquisa = new javax.swing.JPanel();
        Pesquisa = new javax.swing.JTextField();
        Selecao = new javax.swing.JComboBox<>();
        Pesquisar = new javax.swing.JButton();
        PainelRolagem = new javax.swing.JScrollPane();
        Dados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setPreferredSize(new java.awt.Dimension(740, 400));

        PainelPesquisa.setMinimumSize(new java.awt.Dimension(161, 30));
        PainelPesquisa.setPreferredSize(new java.awt.Dimension(743, 30));
        PainelPesquisa.setLayout(new java.awt.GridBagLayout());

        Pesquisa.setToolTipText("Digite aqui a informação a ser pesquisada");
        Pesquisa.setAlignmentY(0.8F);
        Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 350;
        PainelPesquisa.add(Pesquisa, gridBagConstraints);

        Selecao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF", "Logadouro", "E-mail" }));
        Selecao.setToolTipText("Selecione qual o tipo de informação a pesquisar");
        Selecao.setAlignmentX(0.25F);
        Selecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        PainelPesquisa.add(Selecao, gridBagConstraints);

        Pesquisar.setAlignmentX(0.5F);
        Pesquisar.setAlignmentY(0.0F);
        Pesquisar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Pesquisar.setLabel("Pesquisar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        PainelPesquisa.add(Pesquisar, gridBagConstraints);

        getContentPane().add(PainelPesquisa, java.awt.BorderLayout.PAGE_START);

        Dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PainelRolagem.setViewportView(Dados);

        getContentPane().add(PainelRolagem, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelecaoActionPerformed

    private void PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesquisaActionPerformed

    public void preencherTabela(String SQL)
    {
        ArrayList dados= new ArrayList();
        String [] colunas = new String[]{"Nome:","Logadouro:","Email:","CPF:"};
        con.executaSQL(SQL);
        try
        {   
            con.rs.first();    
        do
        {
            dados.add(new Object[]{con.rs.getString("nome"),con.rs.getString("logadouro"),con.rs.getString("e_mail"),con.rs.getString("cpf")});
            JOptionPane.showMessageDialog(null,"foi");
            
        }while(con.rs.next());
        
        }
        catch(SQLException e){
              JOptionPane.showMessageDialog(null,"Erro ao preencher Arraylist");
       }
        
        ModeloTabela tabela = new ModeloTabela(dados, colunas);
        Dados.setModel(tabela);
        Dados.getColumnModel().getColumn(0).setPreferredWidth(80);
        Dados.getColumnModel().getColumn(0).setResizable(true);
        Dados.getColumnModel().getColumn(1).setPreferredWidth(80);
        Dados.getColumnModel().getColumn(1).setResizable(true);
        Dados.getColumnModel().getColumn(2).setPreferredWidth(80);
        Dados.getColumnModel().getColumn(2).setResizable(true);
        Dados.getColumnModel().getColumn(3).setPreferredWidth(80);
        Dados.getColumnModel().getColumn(3).setResizable(true);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaPesquisaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Dados;
    private javax.swing.JPanel PainelPesquisa;
    private javax.swing.JScrollPane PainelRolagem;
    private javax.swing.JTextField Pesquisa;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JComboBox<String> Selecao;
    // End of variables declaration//GEN-END:variables
}
